library(tidyverse)

source("functions.R")

#to read and access file
data_T1 <- read_csv("../data/primary/DiveSite_AbdeensRock_T1.csv")
data_T2 <- read_csv("../data/primary/DiveSite_AbdeensRock_T2.csv")
data_T3 <- read_csv("../data/primary/DiveSite_AbdeensRock_T3.csv")
data_PT1 <- read_csv("../data/primary/Protected_MitriRock_T1.csv")
data_PT2 <- read_csv("../data/primary/Protected_MitriRock_T2.csv")
data_PT3 <- read_csv("../data/primary/Protected_MitriRock_T3.csv")
data2_T1 <- read_csv("../data/primary/Tourist_Helicopter_T1.csv")
data2_T2 <- read_csv("../data/primary/Tourist_Helicopter_T2.csv")
data2_T3 <- read_csv("../data/primary/Tourist_Helicopter_T3.csv")
data2_PT1 <- read_csv("../data/primary/Pagawanen_T1.csv")
data2_PT2 <- read_csv("../data/primary/Pagawanen_T2.csv")
data2_PT3 <- read_csv("../data/primary/Pagawanen_T3.csv")
glimpse(data_T1)
glimpse(data_T2)
glimpse(data_T3)
glimpse(data_PT1)
glimpse(data_PT2)
glimpse(data_PT3)
glimpse(data2_T1)
glimpse(data2_T2)
glimpse(data2_T3)
glimpse(data2_PT1)
glimpse(data2_PT2)
glimpse(data2_PT3)